server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  data:
    redis:
      repositories:
        enabled: false

  redis:
    #数据库索引
    database: 6
    host: 127.0.0.1
    port: 6379
    password:
    #连接超时时间
    timeout: 5000

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.temp.common.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  config: classpath:config/logback-spring.xml
